/* ═══ Vedic Verse — bundled curated corpora for the wider canon ═══
   These are substantial, representative selections of famous, canonical verses
   with public-domain translations — NOT the complete texts. The Gita alone loads
   its full 700-verse dataset live (js/data.js); the Mahabharata (~100k verses) and
   the rest are far too large to ingest at runtime, so we seed each with its most
   quoted passages, structured so more can be appended to the same shape later.

   Translations are public-domain renderings:
     Rig Veda / Atharva — R.T.H. Griffith (1896)
     Upanishads          — F. Max Müller (SBE, 1879–84)
     Mahabharata         — K.M. Ganguli (1883–96)
     Ramayana            — public-domain prose renderings (M.N. Dutt tradition)
     Bhagavata & Puranas — public-domain renderings
     Yoga Sūtras         — public-domain rendering of Patañjali
   Each verse: authentic reference (`cite`), Devanagari where confidently known,
   IAST where helpful, translation, and theme tags used by retrieval + offline voice.

   Verse model (uniform across texts):
     { ch, v, dev, iast, trans, cite, book, themes:[...] }
   `ch` = 1-based index into the text's `sections`; `v` = ordinal within that section.
   The authentic (possibly multi-level) reference lives in `cite`. */
(function () {
  const VV = (window.VV = window.VV || {});

  /* ─────────────────────────── RAMAYANA ─────────────────────────── */
  const RAMAYANA = {
    sections: [
      { n: 1, dev: "बालकाण्ड", en: "Bāla Kāṇḍa", meaning: "The Book of Youth", summary: "Rama's birth in Ayodhya, his boyhood under Vishvamitra, the breaking of Shiva's bow, and his marriage to Sita." },
      { n: 2, dev: "अयोध्याकाण्ड", en: "Ayodhyā Kāṇḍa", meaning: "The Book of Ayodhya", summary: "On the eve of his coronation Rama is exiled for fourteen years; he accepts without bitterness, and Sita and Lakshmana follow him into the forest." },
      { n: 3, dev: "अरण्यकाण्ड", en: "Araṇya Kāṇḍa", meaning: "The Book of the Forest", summary: "Life in the wilderness, the disfiguring of Shurpanakha, and the abduction of Sita by Ravana." },
      { n: 4, dev: "किष्किन्धाकाण्ड", en: "Kiṣkindhā Kāṇḍa", meaning: "The Book of Kishkindha", summary: "Rama's alliance with Sugriva and the vanaras, and the beginning of the search for Sita." },
      { n: 5, dev: "सुन्दरकाण्ड", en: "Sundara Kāṇḍa", meaning: "The Beautiful Book", summary: "Hanuman's leap across the ocean to Lanka, his finding of Sita in the ashoka grove, and the burning of the city." },
      { n: 6, dev: "युद्धकाण्ड", en: "Yuddha Kāṇḍa", meaning: "The Book of War", summary: "The bridge to Lanka, the great war, the fall of Ravana, and the return of Rama to Ayodhya." },
      { n: 7, dev: "उत्तरकाण्ड", en: "Uttara Kāṇḍa", meaning: "The Final Book", summary: "The reign of Rama, the later trials of Sita, and the epic's close." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Rām. 1.2.15", book: "Bāla Kāṇḍa",
        dev: "मा निषाद प्रतिष्ठां त्वमगमः शाश्वतीः समाः।\nयत्क्रौञ्चमिथुनादेकमवधीः काममोहितम्॥",
        iast: "mā niṣāda pratiṣṭhāṃ tvam agamaḥ śāśvatīḥ samāḥ / yat krauñca-mithunād ekam avadhīḥ kāma-mohitam",
        trans: "Hunter, since you killed one of a pair of cranes lost in love, you shall not live long. — grief spoken by the sage Valmiki became the first verse of poetry, born of pity.",
        themes: ["grief", "anger"] },
      { ch: 1, v: 2, cite: "Rām. 1.1.2", book: "Bāla Kāṇḍa",
        dev: "को न्वस्मिन् साम्प्रतं लोके गुणवान् कश्च वीर्यवान्।\nधर्मज्ञश्च कृतज्ञश्च सत्यवाक्यो दृढव्रतः॥",
        iast: "ko nv asmin sāmprataṃ loke guṇavān kaśca vīryavān / dharmajñaśca kṛtajñaśca satyavākyo dṛḍhavrataḥ",
        trans: "Who in this world today is virtuous and truly valiant, who knows what is right, is grateful, truthful of speech, and firm in his vows? — Valmiki's question to Narada, which Rama's life answers.",
        themes: ["purpose", "duty", "knowledge"] },
      { ch: 2, v: 1, cite: "Rām. 2.30 (tradition)", book: "Ayodhyā Kāṇḍa",
        iast: "jananī janma-bhūmiśca svargād api garīyasī",
        dev: "जननी जन्मभूमिश्च स्वर्गादपि गरीयसी।",
        trans: "The mother and the motherland are greater than heaven itself. — Rama's word to Lakshmana, honoring the ground that bore them above any paradise.",
        themes: ["duty", "purpose", "devotion"] },
      { ch: 2, v: 2, cite: "Rām. 2.24 (tradition)", book: "Ayodhyā Kāṇḍa",
        trans: "I do not grieve at leaving the throne, nor at dwelling in the forest; a father's word is a sacred debt, and to keep it is my whole inheritance. — Rama accepting exile without bitterness.",
        themes: ["duty", "surrender", "peace"] },
      { ch: 2, v: 3, cite: "Rām. 2.109 (tradition)", book: "Ayodhyā Kāṇḍa",
        trans: "Truth is the one law that upholds the world; on truth the earth and heavens rest. A man who abandons truth to gain a kingdom has bought ashes with gold. — Rama to Jabali, refusing to break his father's promise.",
        themes: ["knowledge", "duty", "surrender"] },
      { ch: 2, v: 4, cite: "Rām. 2.30 (tradition)", book: "Ayodhyā Kāṇḍa",
        trans: "Where you are, my lord, there is Ayodhya; the forest with you is a city, and a palace without you a wilderness. — Sita, choosing exile beside Rama.",
        themes: ["devotion", "love", "peace"] },
      { ch: 3, v: 1, cite: "Rām. 3.37 (tradition)", book: "Araṇya Kāṇḍa",
        iast: "rāmo vigrahavān dharmaḥ",
        dev: "रामो विग्रहवान् धर्मः।",
        trans: "Rama is righteousness itself, given a body — the good man's refuge, glory made flesh. — even Ravana's counsellor Marica confesses it.",
        themes: ["duty", "knowledge", "purpose"] },
      { ch: 3, v: 2, cite: "Rām. 3.10 (tradition)", book: "Araṇya Kāṇḍa",
        trans: "Though the ascetics of the forest need no defender, a kshatriya who bears the bow is pledged to shelter the helpless; this is the vow I will not lay down. — Rama on protecting the sages.",
        themes: ["duty", "war", "purpose"] },
      { ch: 5, v: 1, cite: "Rām. 5.15 (tradition)", book: "Sundara Kāṇḍa",
        trans: "Wasted by grief yet unbroken in faith, she sat like a flame wrapped in smoke — dimmed, but never extinguished. — Hanuman beholding Sita in the ashoka grove.",
        themes: ["grief", "fear", "surrender"] },
      { ch: 5, v: 2, cite: "Rām. 5.34 (tradition)", book: "Sundara Kāṇḍa",
        trans: "I am the messenger of Rama; take heart — despair is the only defeat, and rescue is already crossing the sea toward you. — Hanuman's word of comfort to Sita.",
        themes: ["fear", "surrender", "devotion"] },
      { ch: 6, v: 1, cite: "Rām. 6.18 (tradition)", book: "Yuddha Kāṇḍa",
        trans: "To one who comes seeking refuge, even but once, saying 'I am yours,' I grant safety from every being — this is my sworn and constant vow. — Rama accepting Vibhishana.",
        themes: ["surrender", "devotion", "peace"] },
      { ch: 6, v: 2, cite: "Rām. 6.116 (tradition)", book: "Yuddha Kāṇḍa",
        trans: "Anger accomplishes nothing but the ruin of the one who holds it; forbearance is the strength of the strong, and forgiveness the ornament of the brave. — the war's hard-won lesson.",
        themes: ["anger", "peace", "war"] },
      { ch: 6, v: 3, cite: "Rām. 6.131 (tradition)", book: "Yuddha Kāṇḍa",
        trans: "As the exile ends and Rama returns, lamps are lit in every window of Ayodhya, and the long night of waiting turns at last to light. — the homecoming that became Dīpāvalī.",
        themes: ["happiness", "peace", "devotion"] },
      { ch: 6, v: 4, cite: "Rām. 6 (tradition)", book: "Yuddha Kāṇḍa",
        trans: "There is no creature that has never erred; even the wrongdoer deserves compassion from the noble. Do not answer cruelty with cruelty. — Sita, forbidding vengeance upon those who had guarded her captivity.",
        themes: ["anger", "peace", "surrender"] },
      { ch: 7, v: 1, cite: "Rām. 7 (tradition)", book: "Uttara Kāṇḍa",
        trans: "In the reign of Rama none wept for want or fear; the rains came in season, the earth gave freely, and every subject spoke the truth and kept to their own duty. — the vision of Rāma-rājya, an order held together by dharma, not force.",
        themes: ["duty", "peace", "purpose"] },
      { ch: 7, v: 2, cite: "Rām. 7 (tradition)", book: "Uttara Kāṇḍa",
        trans: "The king bore the sorrow of his own losses in silence, that the people might carry none; to rule, he learned, is to grieve alone so that others need not. — the loneliness at the heart of duty.",
        themes: ["grief", "duty", "surrender"] }
    ]
  };

  /* ─────────────────────────── MAHABHARATA ─────────────────────────── */
  const MAHABHARATA = {
    sections: [
      { n: 1, dev: "आदिपर्व", en: "Ādi Parva", meaning: "The Book of the Beginning", summary: "The origins of the Kuru line, the birth of the Pandavas and Kauravas, and the seeds of the great rivalry." },
      { n: 2, dev: "वनपर्व", en: "Vana Parva", meaning: "The Book of the Forest", summary: "The Pandavas' twelve years of exile — including the riddles of the Yaksha, where wisdom outweighs strength." },
      { n: 3, dev: "उद्योगपर्व", en: "Udyoga Parva", meaning: "The Book of Effort", summary: "The failed embassy for peace; Vidura's counsel to the blind king Dhritarashtra — the Vidura Nīti." },
      { n: 4, dev: "भीष्मपर्व", en: "Bhīṣma Parva", meaning: "The Book of Bhishma", summary: "The war begins; within it Krishna speaks the Bhagavad Gita to Arjuna." },
      { n: 5, dev: "शान्तिपर्व", en: "Śānti Parva", meaning: "The Book of Peace", summary: "The dying Bhishma teaches Yudhishthira the duties of kings, the nature of dharma, and the way to liberation." },
      { n: 6, dev: "स्त्रीपर्व", en: "Strī Parva", meaning: "The Book of the Women", summary: "The lament of the women over the fallen — the epic's unflinching account of the cost of war." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Mbh. 1.1 (tradition)", book: "Ādi Parva",
        iast: "yad ihāsti tad anyatra yan nehāsti na tat kvacit",
        dev: "यदिहास्ति तदन्यत्र यन्नेहास्ति न तत्क्वचित्।",
        trans: "What is found here — of dharma, of gain, of pleasure and of freedom — may be found elsewhere; but what is not here is nowhere else to be found. — the epic's claim upon the whole of life.",
        themes: ["knowledge", "purpose", "duty"] },
      { ch: 1, v: 2, cite: "Mbh. 1.85 (tradition)", book: "Ādi Parva",
        iast: "na jātu kāmaḥ kāmānām upabhogena śāmyati",
        dev: "न जातु कामः कामानामुपभोगेन शाम्यति।\nहविषा कृष्णवर्त्मेव भूय एवाभिवर्धते॥",
        trans: "Desire is never quenched by the enjoyment of what is desired; like fire fed with butter, it only blazes the higher. — King Yayati, at the end of a life of pleasure.",
        themes: ["desire", "happiness", "peace"] },
      { ch: 2, v: 1, cite: "Mbh. 3.313 (Yakṣa Praśna)", book: "Vana Parva",
        dev: "अहन्यहनि भूतानि गच्छन्ति यममन्दिरम्।\nशेषाः स्थावरमिच्छन्ति किमाश्चर्यमतः परम्॥",
        iast: "ahany ahani bhūtāni gacchanti yama-mandiram / śeṣāḥ sthiram icchanti kim āścaryam ataḥ param",
        trans: "Day after day countless beings depart to the house of death, yet those who remain believe themselves immortal. What could be a greater wonder? — Yudhishthira answering the Yaksha.",
        themes: ["death", "knowledge", "desire"] },
      { ch: 2, v: 2, cite: "Mbh. 3.313 (Yakṣa Praśna)", book: "Vana Parva",
        trans: "'What is the path?' asked the Yaksha. Reasoning leads nowhere certain, scriptures disagree, and no single sage holds the whole truth; the path is the road walked by the great-souled. — Yudhishthira's answer.",
        themes: ["purpose", "knowledge", "duty"] },
      { ch: 2, v: 3, cite: "Mbh. 3.313 (Yakṣa Praśna)", book: "Vana Parva",
        trans: "'What makes one truly wealthy, and what is true news?' Contentment is the highest wealth; and the news is this — that in the great cooking-pot of time, the sun the fire, days and nights the fuel, creatures are cooked. That is the tidings of the world.",
        themes: ["happiness", "death", "knowledge"] },
      { ch: 3, v: 1, cite: "Mbh. 5.33 (Vidura Nīti)", book: "Udyoga Parva",
        trans: "He is wise whose plans no one knows until they bear fruit, who is not turned from his purpose by cold or heat, fear or fortune, wealth or want. — Vidura on the marks of the wise.",
        themes: ["knowledge", "mind", "peace"] },
      { ch: 3, v: 2, cite: "Mbh. 5.34 (Vidura Nīti)", book: "Udyoga Parva",
        trans: "Anger is a bitter, harsh medicine — one draught cures every sorrow, for the man who can swallow his own rage endures what no weapon can pierce. — Vidura to Dhritarashtra.",
        themes: ["anger", "peace", "mind"] },
      { ch: 3, v: 3, cite: "Mbh. 5.34 (Vidura Nīti)", book: "Udyoga Parva",
        trans: "The one who forgives, and the one who is patient — both dwell in happiness; the impatient man is ruined, whether he wins or loses. Forgiveness is the might of the mighty. — Vidura's counsel.",
        themes: ["anger", "peace", "failure"] },
      { ch: 3, v: 4, cite: "Mbh. 5.35 (Vidura Nīti)", book: "Udyoga Parva",
        trans: "As one small lamp may kindle many and lose nothing of its own flame, so a wise man who shares his knowledge grows no poorer, and the world grows bright. — on the giving of wisdom.",
        themes: ["knowledge", "devotion", "purpose"] },
      { ch: 4, v: 1, cite: "Mbh. 6 (tradition)", book: "Bhīṣma Parva",
        iast: "yato dharmas tato jayaḥ",
        dev: "यतो धर्मस्ततो जयः।",
        trans: "Where there is righteousness, there is victory. — the refrain sounded again and again across the eighteen days of war.",
        themes: ["war", "duty", "purpose"] },
      { ch: 5, v: 1, cite: "Mbh. 13.117 (tradition)", book: "Śānti Parva",
        iast: "ahiṃsā paramo dharmaḥ",
        dev: "अहिंसा परमो धर्मः।",
        trans: "Non-violence is the highest dharma — and so too is the righteous restraint of harm; the two are not enemies but the same compassion, seen from two sides. — Bhishma's teaching.",
        themes: ["war", "peace", "duty"] },
      { ch: 5, v: 2, cite: "Mbh. 12 (tradition)", book: "Śānti Parva",
        trans: "Do not do to another what you would count as a wound if done to you; this is the whole of dharma — the rest is commentary. — Bhishma to Yudhishthira.",
        themes: ["duty", "peace", "knowledge"] },
      { ch: 5, v: 3, cite: "Mbh. 12 (tradition)", book: "Śānti Parva",
        trans: "Grief kills far more surely than any disease; the grieving man loses his beauty, his strength, his wisdom — mourn, but do not let mourning consume the one who still must live. — the counsel to the bereaved king.",
        themes: ["grief", "death", "peace"] },
      { ch: 6, v: 1, cite: "Mbh. 11 (tradition)", book: "Strī Parva",
        trans: "Look on the field where sons and fathers lie together, and ask what was won: victory and defeat wear the same ash-grey face when the fires burn low. — the lament of Gandhari.",
        themes: ["war", "grief", "failure"] }
    ]
  };

  /* ─────────────────────────── THE VEDAS ─────────────────────────── */
  const VEDAS = {
    sections: [
      { n: 1, dev: "ऋग्वेदः", en: "Ṛgveda", meaning: "The Veda of Hymns", summary: "The oldest layer — hymns of praise and cosmic wonder to the powers of nature and the ground of being." },
      { n: 2, dev: "यजुर्वेदः", en: "Yajurveda", meaning: "The Veda of Ritual", summary: "The formulas of sacrifice and the inward turn from rite to meaning." },
      { n: 3, dev: "सामवेदः", en: "Sāmaveda", meaning: "The Veda of Chant", summary: "The Rigveda's verses set to melody — worship as music." },
      { n: 4, dev: "अथर्ववेदः", en: "Atharvaveda", meaning: "The Veda of the Everyday", summary: "Hymns of healing, home, earth and daily life — the sacred woven into the ordinary." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Ṛgveda 10.129.1", book: "Ṛgveda — Nāsadīya Sūkta",
        dev: "नासदासीन्नो सदासीत्तदानीं नासीद्रजो नो व्योमा परो यत्।",
        iast: "nāsad āsīn no sad āsīt tadānīṃ",
        trans: "Then was not non-existent nor existent: there was no realm of air, no sky beyond it. What covered in, and where? and what gave shelter? Was water there, unfathomed depth of water? — the Hymn of Creation.",
        themes: ["knowledge", "death", "peace"] },
      { ch: 1, v: 2, cite: "Ṛgveda 10.129.7", book: "Ṛgveda — Nāsadīya Sūkta",
        trans: "Whence all creation had its origin, whether he formed it all or did not form it, whose eye controls this world in highest heaven — he verily knows it, or perhaps he knows not. — creation ending in a question, not a claim.",
        themes: ["knowledge", "surrender", "peace"] },
      { ch: 1, v: 3, cite: "Ṛgveda 1.164.46", book: "Ṛgveda",
        dev: "एकं सद्विप्रा बहुधा वदन्ति।",
        iast: "ekaṃ sad viprā bahudhā vadanti",
        trans: "They call him Indra, Mitra, Varuna, Agni... To what is One, sages give many a title. — the root of a thousand paths held as one truth.",
        themes: ["knowledge", "devotion", "peace"] },
      { ch: 1, v: 4, cite: "Ṛgveda 3.62.10", book: "Ṛgveda — the Gāyatrī",
        dev: "तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि।\nधियो यो नः प्रचोदयात्॥",
        iast: "tat savitur vareṇyaṃ bhargo devasya dhīmahi / dhiyo yo naḥ pracodayāt",
        trans: "May we attain that excellent glory of Savitar the God, so may he stimulate our prayers. — the Gāyatrī, the most repeated prayer of the tradition.",
        themes: ["meditation", "knowledge", "devotion"] },
      { ch: 1, v: 5, cite: "Ṛgveda 1.89.1", book: "Ṛgveda",
        dev: "आ नो भद्राः क्रतवो यन्तु विश्वतः।",
        iast: "ā no bhadrāḥ kratavo yantu viśvataḥ",
        trans: "Let noble thoughts come to us from every side — unchecked, undeceived, and expanding on all sides. — a prayer for an open mind.",
        themes: ["mind", "knowledge", "peace"] },
      { ch: 1, v: 6, cite: "Ṛgveda 10.191.2", book: "Ṛgveda — Saṃjñāna Sūkta",
        dev: "सं गच्छध्वं सं वदध्वं सं वो मनांसि जानताम्।",
        iast: "saṃ gacchadhvaṃ saṃ vadadhvaṃ saṃ vo manāṃsi jānatām",
        trans: "Meet together, speak together, let your minds be of one accord — united your resolve, united your hearts, may your spirits be at one. — the closing hymn on concord.",
        themes: ["peace", "devotion", "purpose"] },
      { ch: 2, v: 1, cite: "Yajurveda 36.17 (Śānti)", book: "Yajurveda",
        dev: "ॐ द्यौः शान्तिरन्तरिक्षं शान्तिः पृथिवी शान्तिः।",
        iast: "oṃ dyauḥ śāntir antarikṣaṃ śāntiḥ pṛthivī śāntiḥ",
        trans: "May there be peace in the heavens, peace in the sky, peace on the earth; peace in the waters, the plants, the forests; peace in all, and peace upon that peace. — the great Śānti mantra.",
        themes: ["peace", "meditation", "devotion"] },
      { ch: 4, v: 1, cite: "Atharvaveda 12.1.12", book: "Atharvaveda — Bhūmi Sūkta",
        dev: "माता भूमिः पुत्रोऽहं पृथिव्याः।",
        iast: "mātā bhūmiḥ putro 'haṃ pṛthivyāḥ",
        trans: "The Earth is my mother, and I am her son. May she who bears the burden of the world grant us prosperity and peace. — the Hymn to the Earth.",
        themes: ["devotion", "peace", "purpose"] },
      { ch: 4, v: 2, cite: "Atharvaveda 19.9.14", book: "Atharvaveda",
        trans: "Peaceful be the earth, peaceful the ether, peaceful the heaven, peaceful the waters, peaceful the herbs; may all bring peace to us. — a blessing for a settled heart.",
        themes: ["peace", "fear", "meditation"] }
    ]
  };

  /* ─────────────────────────── THE UPANISHADS ─────────────────────────── */
  const UPANISHADS = {
    sections: [
      { n: 1, dev: "प्रधान उपनिषदः", en: "The Principal Upanishads", meaning: "The teaching that sits close", summary: "The philosophical crown of the Vedas — the inward turn from ritual to the Self, from the many to the One." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Īśa Up. 1", book: "Īśa Upanishad",
        dev: "ईशावास्यमिदं सर्वं यत्किञ्च जगत्यां जगत्।\nतेन त्यक्तेन भुञ्जीथा मा गृधः कस्यस्विद्धनम्॥",
        iast: "īśāvāsyam idaṃ sarvaṃ yat kiñca jagatyāṃ jagat / tena tyaktena bhuñjīthā mā gṛdhaḥ kasyasvid dhanam",
        trans: "Whatever moves in this moving world is pervaded by the Lord. Enjoy it through renunciation; do not covet, for whose is wealth? — the opening of the Īśa.",
        themes: ["surrender", "desire", "knowledge"] },
      { ch: 1, v: 2, cite: "Bṛhadāraṇyaka Up. 1.3.28", book: "Bṛhadāraṇyaka Upanishad",
        dev: "असतो मा सद्गमय। तमसो मा ज्योतिर्गमय। मृत्योर्मा अमृतं गमय॥",
        iast: "asato mā sad gamaya / tamaso mā jyotir gamaya / mṛtyor mā amṛtaṃ gamaya",
        trans: "Lead me from the unreal to the real; lead me from darkness to light; lead me from death to immortality. — the prayer of the seeker.",
        themes: ["knowledge", "death", "surrender"] },
      { ch: 1, v: 3, cite: "Bṛhadāraṇyaka Up. 1.4.10", book: "Bṛhadāraṇyaka Upanishad",
        dev: "अहं ब्रह्मास्मि।",
        iast: "ahaṃ brahmāsmi",
        trans: "'I am Brahman.' Whoever knows this becomes the All; not even the gods can prevent it, for he becomes their very Self. — the great utterance.",
        themes: ["knowledge", "surrender", "peace"] },
      { ch: 1, v: 4, cite: "Chāndogya Up. 6.8.7", book: "Chāndogya Upanishad",
        dev: "तत्त्वमसि।",
        iast: "tat tvam asi",
        trans: "That which is the subtle essence — in it all that exists has its self. It is the True. It is the Self. And that, Śvetaketu, THAT THOU ART. — the father's teaching to his son.",
        themes: ["knowledge", "peace", "surrender"] },
      { ch: 1, v: 5, cite: "Kaṭha Up. 1.2.20", book: "Kaṭha Upanishad",
        dev: "अणोरणीयान्महतो महीयानात्माऽस्य जन्तोर्निहितो गुहायाम्।",
        iast: "aṇor aṇīyān mahato mahīyān ātmā'sya jantor nihito guhāyām",
        trans: "Smaller than the small, greater than the great, the Self is hidden in the heart of every creature. Free of craving, calm of mind, one beholds the majesty of the Self, and grief falls away.",
        themes: ["knowledge", "grief", "meditation"] },
      { ch: 1, v: 6, cite: "Kaṭha Up. 1.2.18", book: "Kaṭha Upanishad",
        dev: "न जायते म्रियते वा विपश्चिन्नायं कुतश्चिन्न बभूव कश्चित्।",
        iast: "na jāyate mriyate vā vipaścin nāyaṃ kutaścin na babhūva kaścit",
        trans: "The knowing Self is never born, nor does it die; it did not come from anywhere, nor did anything become it. Unborn, eternal, ancient — it is not slain when the body is slain.",
        themes: ["death", "grief", "knowledge"] },
      { ch: 1, v: 7, cite: "Kaṭha Up. 1.3.14", book: "Kaṭha Upanishad",
        dev: "उत्तिष्ठत जाग्रत प्राप्य वरान्निबोधत।",
        iast: "uttiṣṭhata jāgrata prāpya varān nibodhata",
        trans: "Arise! Awake! Approach the great ones and learn. Sharp as a razor's edge is the path, the poets say — hard to tread and difficult to cross.",
        themes: ["purpose", "duty", "knowledge"] },
      { ch: 1, v: 8, cite: "Muṇḍaka Up. 3.1.6", book: "Muṇḍaka Upanishad",
        dev: "सत्यमेव जयते नानृतं।",
        iast: "satyam eva jayate nānṛtaṃ",
        trans: "Truth alone triumphs, not falsehood; by truth is laid the path by which the sages, their desires fulfilled, ascend to where Truth has its supreme abode. — India's national motto.",
        themes: ["knowledge", "purpose", "duty"] },
      { ch: 1, v: 9, cite: "Muṇḍaka Up. 3.1.1", book: "Muṇḍaka Upanishad",
        dev: "द्वा सुपर्णा सयुजा सखाया समानं वृक्षं परिषस्वजाते।",
        iast: "dvā suparṇā sayujā sakhāyā samānaṃ vṛkṣaṃ pariṣasvajāte",
        trans: "Two birds, inseparable companions, perch on the same tree. One eats the sweet fruit; the other looks on without eating. — the soul that consumes and the Self that witnesses.",
        themes: ["knowledge", "desire", "peace"] },
      { ch: 1, v: 10, cite: "Kena Up. 1.3", book: "Kena Upanishad",
        trans: "There the eye does not go, nor speech, nor mind; we do not know, we do not understand how one can teach it. It is other than the known, and beyond the unknown. — on that which cannot be grasped.",
        themes: ["knowledge", "meditation", "surrender"] },
      { ch: 1, v: 11, cite: "Taittirīya Up. 1.11.1", book: "Taittirīya Upanishad",
        dev: "सत्यं वद। धर्मं चर।",
        iast: "satyaṃ vada / dharmaṃ cara",
        trans: "Speak the truth. Practice righteousness. Do not neglect your own welfare; do not neglect what is good. — the graduate's charge, the oldest commencement address.",
        themes: ["duty", "purpose", "knowledge"] },
      { ch: 1, v: 12, cite: "Māṇḍūkya Up. 1", book: "Māṇḍūkya Upanishad",
        dev: "ॐ इत्येतदक्षरमिदं सर्वम्।",
        iast: "oṃ ity etad akṣaram idaṃ sarvam",
        trans: "AUM — this syllable is all this. All that is past, present, and future is AUM; and whatever is beyond the three times, that too is AUM. — the sound in which everything is held.",
        themes: ["meditation", "knowledge", "peace"] },
      { ch: 1, v: 13, cite: "Īśa Up. (Śānti)", book: "Īśa Upanishad — invocation",
        dev: "ॐ पूर्णमदः पूर्णमिदं पूर्णात्पूर्णमुदच्यते।\nपूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते॥",
        iast: "oṃ pūrṇam adaḥ pūrṇam idaṃ pūrṇāt pūrṇam udacyate",
        trans: "That is whole; this is whole. From the whole, the whole arises. Take the whole from the whole, and the whole yet remains. — the mathematics of the infinite.",
        themes: ["knowledge", "peace", "happiness"] },
      { ch: 1, v: 14, cite: "Chāndogya Up. 3.14.1", book: "Chāndogya Upanishad",
        dev: "सर्वं खल्विदं ब्रह्म।",
        iast: "sarvaṃ khalv idaṃ brahma",
        trans: "All this is Brahman. Let one meditate with a tranquil mind on this world as beginning, ending and breathing in Brahman. — the wide vision that steadies the heart.",
        themes: ["knowledge", "peace", "meditation"] },
      { ch: 1, v: 15, cite: "Bṛhadāraṇyaka Up. 2.3.6", book: "Bṛhadāraṇyaka Upanishad",
        dev: "नेति नेति।",
        iast: "neti neti",
        trans: "Of the Self one can only say: not this, not this. It is ungraspable, for it cannot be grasped; indestructible, for it cannot be destroyed. — the way of negation that clears every idol away.",
        themes: ["knowledge", "surrender", "meditation"] },
      { ch: 1, v: 16, cite: "Muṇḍaka Up. 3.2.9", book: "Muṇḍaka Upanishad",
        dev: "ब्रह्मविद् ब्रह्मैव भवति।",
        iast: "brahmavid brahmaiva bhavati",
        trans: "One who knows that supreme Brahman becomes Brahman itself. He crosses beyond sorrow, crosses beyond sin, and freed from the knots of the heart, becomes immortal. — knowing as becoming.",
        themes: ["knowledge", "grief", "surrender"] },
      { ch: 1, v: 17, cite: "Taittirīya Up. 2.7", book: "Taittirīya Upanishad",
        dev: "रसो वै सः। रसं ह्येवायं लब्ध्वाऽऽनन्दी भवति।",
        iast: "raso vai saḥ; rasaṃ hy evāyaṃ labdhvānandī bhavati",
        trans: "He is the very essence — the savour of all things. For only on reaching this essence does one become full of bliss. — joy is not added to us; it is what we are made of.",
        themes: ["happiness", "knowledge", "peace"] },
      { ch: 1, v: 18, cite: "Kaṭha Up. 1.2.23", book: "Kaṭha Upanishad",
        dev: "नायमात्मा प्रवचनेन लभ्यो न मेधया न बहुना श्रुतेन।",
        iast: "nāyam ātmā pravacanena labhyo na medhayā na bahunā śrutena",
        trans: "This Self is not won by discourse, nor by intellect, nor by much hearing of scripture. It is won only by the one it chooses — to such a one the Self reveals its own form. — grace, not effort alone.",
        themes: ["knowledge", "surrender", "devotion"] }
    ]
  };

  /* ─────────────────────────── THE PURANAS ─────────────────────────── */
  const PURANAS = {
    sections: [
      { n: 1, dev: "श्रीमद्भागवतम्", en: "Bhāgavata Purāṇa", meaning: "The Story of the Fortunate One", summary: "The best-loved Purana — the deeds of Vishnu and Krishna, and the ripening of devotion into knowledge." },
      { n: 2, dev: "विष्णुपुराणम्", en: "Viṣṇu Purāṇa", meaning: "The Purana of Vishnu", summary: "Cosmology, the ages of the world, and the sustaining power that holds all things." },
      { n: 3, dev: "देवीमाहात्म्यम्", en: "Devī Māhātmya", meaning: "The Glory of the Goddess", summary: "From the Markandeya Purana — the Mother as the power (śakti) present in all beings." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Bhāgavata 1.2.11", book: "Bhāgavata Purāṇa",
        dev: "वदन्ति तत्तत्त्वविदस्तत्त्वं यज्ज्ञानमद्वयम्।\nब्रह्मेति परमात्मेति भगवानिति शब्द्यते॥",
        iast: "vadanti tat tattva-vidas tattvaṃ yaj jñānam advayam / brahmeti paramātmeti bhagavān iti śabdyate",
        trans: "The knowers of truth call that non-dual reality by three names — Brahman, the Supreme Self, and Bhagavān; one truth, seen from the paths of knowledge, meditation, and love.",
        themes: ["knowledge", "devotion", "meditation"] },
      { ch: 1, v: 2, cite: "Bhāgavata 7.5.23", book: "Bhāgavata Purāṇa — Prahlāda",
        dev: "श्रवणं कीर्तनं विष्णोः स्मरणं पादसेवनम्।\nअर्चनं वन्दनं दास्यं सख्यमात्मनिवेदनम्॥",
        iast: "śravaṇaṃ kīrtanaṃ viṣṇoḥ smaraṇaṃ pāda-sevanam",
        trans: "Hearing, singing, remembering, serving, worshipping, bowing, being a servant, a friend, and offering the whole self — these are the nine ways of love. — the boy-saint Prahlāda.",
        themes: ["devotion", "meditation", "surrender"] },
      { ch: 1, v: 3, cite: "Bhāgavata 8.3 (Gajendra)", book: "Bhāgavata Purāṇa — Gajendra",
        trans: "When his own strength was spent and no help came, the elephant lifted a single lotus and cried out to the Lord alone — and that cry, emptied of all self-reliance, was answered at once. — the surrender of Gajendra.",
        themes: ["surrender", "fear", "devotion"] },
      { ch: 1, v: 4, cite: "Bhāgavata 11.2.42", book: "Bhāgavata Purāṇa",
        trans: "Devotion, direct experience of the Lord, and detachment from all else are born together in one who is surrendered — as a man eating is at once nourished, satisfied, and freed from hunger with every bite.",
        themes: ["devotion", "desire", "knowledge"] },
      { ch: 2, v: 1, cite: "Viṣṇu Purāṇa 1.22", book: "Viṣṇu Purāṇa",
        trans: "As threads issue from the spider and are drawn back again, so from the imperishable One the whole world arises and returns; he is the weaver, the loom, and the cloth. — on the ground of all.",
        themes: ["knowledge", "death", "peace"] },
      { ch: 2, v: 2, cite: "Viṣṇu Purāṇa 6.2", book: "Viṣṇu Purāṇa — on the Kali age",
        trans: "In the dark age virtue is thin, but its one great mercy is this: what took long austerity in former ages is now gained by simple remembrance of the Divine Name. — the grace hidden in a hard time.",
        themes: ["devotion", "failure", "surrender"] },
      { ch: 3, v: 1, cite: "Devī Māhātmya 5", book: "Devī Māhātmya",
        dev: "या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता।\nनमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥",
        iast: "yā devī sarva-bhūteṣu śakti-rūpeṇa saṃsthitā",
        trans: "To the Goddess who abides in all beings as power, as peace, as mercy, as consciousness itself — to Her we bow, and bow, and bow again. — the litany of the Mother.",
        themes: ["devotion", "peace", "meditation"] },
      { ch: 3, v: 2, cite: "Devī Māhātmya 1", book: "Devī Māhātmya",
        trans: "Even the wise, dragged by her power of illusion, are cast into the whirlpool of attachment; she is at once the bondage of the world and the boat that carries us across it.",
        themes: ["desire", "surrender", "knowledge"] }
    ]
  };

  /* ─────────────── YOGA SŪTRAS & THE PATH OF DHARMA ─────────────── */
  const YOGA = {
    sections: [
      { n: 1, dev: "पातञ्जलयोगसूत्राणि", en: "Pātañjala Yoga Sūtras", meaning: "The Aphorisms of Patañjali", summary: "The classical map of yoga — how the restless mind is stilled, and what is found when it is." },
      { n: 2, dev: "धर्मशास्त्रम्", en: "The Path of Dharma", meaning: "The way of right conduct", summary: "Verses on truthful speech, restraint, and the law that upholds the one who upholds it." }
    ],
    verses: [
      { ch: 1, v: 1, cite: "Yoga Sūtra 1.2", book: "Yoga Sūtras — Samādhi Pāda",
        dev: "योगश्चित्तवृत्तिनिरोधः।",
        iast: "yogaś citta-vṛtti-nirodhaḥ",
        trans: "Yoga is the stilling of the fluctuations of the mind. — the whole science in four words; everything after is method.",
        themes: ["mind", "meditation", "peace"] },
      { ch: 1, v: 2, cite: "Yoga Sūtra 1.3", book: "Yoga Sūtras — Samādhi Pāda",
        dev: "तदा द्रष्टुः स्वरूपेऽवस्थानम्।",
        iast: "tadā draṣṭuḥ svarūpe 'vasthānam",
        trans: "Then the seer abides in its own true nature. — when the waters go still, the one who was always looking is finally seen.",
        themes: ["meditation", "knowledge", "peace"] },
      { ch: 1, v: 3, cite: "Yoga Sūtra 1.12", book: "Yoga Sūtras — Samādhi Pāda",
        dev: "अभ्यासवैराग्याभ्यां तन्निरोधः।",
        iast: "abhyāsa-vairāgyābhyāṃ tan-nirodhaḥ",
        trans: "The stilling of the mind comes through practice and non-attachment — steady repetition on one side, the loosening of craving on the other. — the two wings of the whole path.",
        themes: ["mind", "desire", "meditation"] },
      { ch: 1, v: 4, cite: "Yoga Sūtra 1.14", book: "Yoga Sūtras — Samādhi Pāda",
        iast: "sa tu dīrgha-kāla-nairantarya-satkārāsevito dṛḍha-bhūmiḥ",
        trans: "Practice becomes firmly grounded when it is pursued for a long time, without interruption, and with devotion. — there is no shortcut, only faithfulness.",
        themes: ["mind", "purpose", "failure"] },
      { ch: 1, v: 5, cite: "Yoga Sūtra 1.33", book: "Yoga Sūtras — Samādhi Pāda",
        dev: "मैत्रीकरुणामुदितोपेक्षाणां... भावनातश्चित्तप्रसादनम्।",
        iast: "maitrī-karuṇā-muditopekṣāṇāṃ ... citta-prasādanam",
        trans: "The mind becomes clear and serene by cultivating friendliness toward the happy, compassion for the suffering, gladness at the good, and equanimity toward the flawed. — four attitudes that calm the heart.",
        themes: ["peace", "anger", "mind"] },
      { ch: 1, v: 6, cite: "Yoga Sūtra 2.46", book: "Yoga Sūtras — Sādhana Pāda",
        dev: "स्थिरसुखमासनम्।",
        iast: "sthira-sukham āsanam",
        trans: "The posture should be steady and comfortable. — the seat of yoga, and a rule for the whole of life: firmness and ease, held together.",
        themes: ["meditation", "peace", "mind"] },
      { ch: 1, v: 7, cite: "Yoga Sūtra 2.16", book: "Yoga Sūtras — Sādhana Pāda",
        dev: "हेयं दुःखमनागतम्।",
        iast: "heyaṃ duḥkham anāgatam",
        trans: "The suffering that has not yet come is the suffering to be avoided. — the past cannot be changed and the present must be met; wisdom works on the sorrow still upstream.",
        themes: ["fear", "grief", "mind"] },
      { ch: 2, v: 1, cite: "Manusmṛti 8.15", book: "The Path of Dharma",
        dev: "धर्म एव हतो हन्ति धर्मो रक्षति रक्षितः।",
        iast: "dharma eva hato hanti dharmo rakṣati rakṣitaḥ",
        trans: "Dharma, when destroyed, destroys; dharma, when protected, protects. Therefore let no one lay dharma waste, lest it lay us waste in turn. — the reciprocity of righteousness.",
        themes: ["duty", "purpose", "failure"] },
      { ch: 2, v: 2, cite: "Manusmṛti 4.138", book: "The Path of Dharma",
        dev: "सत्यं ब्रूयात् प्रियं ब्रूयान्न ब्रूयात् सत्यमप्रियम्।",
        iast: "satyaṃ brūyāt priyaṃ brūyān na brūyāt satyam apriyam",
        trans: "Speak the truth, and speak it kindly; do not speak a truth that only wounds, nor a pleasant falsehood — this is the eternal law of good speech.",
        themes: ["duty", "peace", "knowledge"] },
      { ch: 2, v: 3, cite: "Dharma tradition", book: "The Path of Dharma",
        dev: "अहिंसा सत्यमस्तेयं शौचमिन्द्रियनिग्रहः।",
        iast: "ahiṃsā satyam asteyaṃ śaucam indriya-nigrahaḥ",
        trans: "Non-harming, truthfulness, not taking what is not given, purity, and mastery of the senses — this is the fivefold ground on which every higher discipline is built.",
        themes: ["duty", "desire", "peace"] }
    ]
  };

  /* the bundled corpora, keyed by text id */
  VV.CORPORA = {
    ramayana: RAMAYANA,
    mahabharata: MAHABHARATA,
    vedas: VEDAS,
    upanishads: UPANISHADS,
    puranas: PURANAS,
    yoga: YOGA
  };
})();
